import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const inter = Inter({
  variable: "--font-inter-sans",
  weight: ["400"],
  subsets: ["latin"],
});

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
};

export const metadata: Metadata = {
  title: {
    default: "TecClub Monitor",
    template: "%s | TecClub Monitor",
  },

  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`bg-background text-foreground font-sans antialiased ${inter.variable}`}
      >
        <Providers
          themeProps={{ attribute: "class", defaultTheme: "light" }}
          className="min-h-screen"
        >
          {children}
        </Providers>
      </body>
    </html>
  );
}
